# This is a stub file generated from the original Python module

CallMeMaybe: ...
FlexUnPack: ...
NothingAtAll: ...
ProceduralError: ...
_CallMeMaybe: ...
_HereIsMyNumber: ...
_ThisIsCrazy: ...
_TryToChaseMe: ...
abstractmethod: ...
annotations: ...
collections: ...
ic: ...
maybe: ...
newCallMeMaybe: ...
typing: ...
