# This is a stub file generated from the original Python module

Ann: ...
Any: ...
CallMeMaybe: ...
TypeAlias: ...
TypeGuardError: ...
TypeGuardFunction: ...
Union: ...
annotations: ...
builtins: ...
empty: ...
maybe: ...
maybeTypes: ...
n00bError: ...
searchKeys: ...
stringList: ...
typeGuard: ...
