# This is a stub file generated from the original Python module

CallMeMaybe: ...
ClassDecorator: ...
Decorator: ...
NoReturn: ...
ValidationError: ...
abstractmethod: ...
annotations: ...
n00bError: ...
