# This is a stub file generated from the original Python module

Acc: ...
Any: ...
CallMeMaybe: ...
Field: ...
FieldApply: ...
Name: ...
Never: ...
NoReturn: ...
Perm: ...
ReadOnlyError: ...
_FieldPropMixin: ...
annotations: ...
applicator: ...
maybe: ...
searchKeys: ...
stringList: ...
