# This is a stub file generated from the original Python module

Container: ...
CopyClass: ...
CopyMeta: ...
Numerical: ...
TypeBag: ...
TypeBagParent: ...
_TypeBag: ...
_parseType: ...
annotations: ...
ic: ...
typing: ...
unPack: ...
unStupid: ...
union: ...
