"""``EZSpaceHook`` integrates field collection and method
auto-generation with the metaclass namespace pipeline.

It runs in two places:

- ``setItemPhase``: rejects definitions of reserved-dunder names
  unless the value is ``@trust``-decorated (in which case the
  value is dropped from the namespace and replaced later).
- ``postCompilePhase``: collects fields, validates orderability if
  requested, sets ``__slots__`` and ``__slot_objects__`` on the
  compiled namespace, and installs the auto-generated dunder
  methods using ``setdefault`` so user-defined overrides are
  preserved."""
#  AGPL-3.0 license
#  Copyright (c) 2025-2026 Asger Jon Vistisen
from __future__ import annotations

from typing import TYPE_CHECKING

from ..mcls.space_hooks import AbstractSpaceHook
from ..waitaminute.meta import ReservedName
from ._collect_fields import collectFields
from ._make_as_dict import makeAsDict
from ._make_as_tuple import makeAsTuple
from ._make_del_attr import makeDelAttr
from ._make_del_item import makeDelItem
from ._make_eq import makeEq
from ._make_get_item import makeGetItem
from ._make_hash import makeHash
from ._make_init import makeInit
from ._make_iter import makeIter
from ._make_len import makeLen
from ._make_ordering_op import makeOrderingOp
from ._make_repr import makeRepr
from ._make_set_attr import makeSetAttr
from ._make_set_item import makeSetItem
from ._make_str import makeStr
from ._validate_orderable import validateOrderable

if TYPE_CHECKING:  # pragma: no cover
  from typing import Any

#  Names auto-generated by EZMeta. User definitions of these names
#  are rejected at setItemPhase unless the value is decorated with
#  ``@trust``. Note ``__str__`` and ``__repr__`` are intentionally
#  absent so users can override them freely.
_RESERVED_DUNDERS = frozenset({
  '__init__',
  '__eq__',
  '__hash__',
  '__iter__',
  '__len__',
  '__getitem__',
  '__setitem__',
  '__delitem__',
  '__getattr__',
  '__setattr__',
  '__delattr__',
  '__lt__',
  '__le__',
  '__gt__',
  '__ge__',
}
)


class EZSpaceHook(AbstractSpaceHook):
  """Field-collecting and method-installing hook for ``EZSpace``."""

  def setItemPhase(
      self, key: str, val: Any, old: Any = None,
  ) -> bool:
    if key in _RESERVED_DUNDERS:
      if getattr(val, '__is_root__', False):
        return True
      raise ReservedName(key)
    return False

  def postCompilePhase(self, compiledSpace: dict) -> dict:
    bases = self.space.getBases()
    classKwargs = self.space.getKwargs() or {}
    notations = compiledSpace.get('__notations__', {}) or {}
    className = self.space.getClassName()
    frozen = bool(classKwargs.get('frozen', False))
    ordered = bool(classKwargs.get('order', False))
    fields = collectFields(
      compiledSpace, bases, notations, className
    )
    if ordered:
      validateOrderable(fields, className)
    compiledSpace['__slot_objects__'] = tuple(fields)
    slots = tuple(f.name for f in fields)
    if frozen:
      slots = slots + ('__ez_initialized__',)
    compiledSpace['__slots__'] = slots
    generated = {
      '__init__'   : makeInit(fields, frozen),
      '__eq__'     : makeEq(fields),
      '__hash__'   : makeHash(fields, frozen),
      '__repr__'   : makeRepr(fields),
      '__str__'    : makeStr(fields),
      '__iter__'   : makeIter(fields),
      '__len__'    : makeLen(fields),
      '__getitem__': makeGetItem(fields),
      '__setitem__': makeSetItem(fields),
      '__delitem__': makeDelItem(),
      '__setattr__': makeSetAttr(fields, frozen),
      '__delattr__': makeDelAttr(),
      '__lt__'     : makeOrderingOp(fields, '<', ordered),
      '__le__'     : makeOrderingOp(fields, '<=', ordered),
      '__gt__'     : makeOrderingOp(fields, '>', ordered),
      '__ge__'     : makeOrderingOp(fields, '>=', ordered),
      'asTuple'    : makeAsTuple(fields),
      'asDict'     : makeAsDict(fields),
    }
    for name, value in generated.items():
      compiledSpace.setdefault(name, value)
    return compiledSpace
