"""The ``trust`` decorator marks methods that should bypass the
``EZData`` reserved-name guard.

When a method's name overlaps with one of the dunder methods
generated by ``EZMeta`` (``__init__``, ``__eq__``, etc.), the
namespace hook normally rejects the definition with
``ReservedName``. Decorating the method with ``@trust`` opts out
of that check; the decorated body is then ignored, and the
metaclass installs its auto-generated implementation at that
name."""
#  AGPL-3.0 license
#  Copyright (c) 2025-2026 Asger Jon Vistisen
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:  # pragma: no cover
  from typing import Callable


def trust(callMeMaybe: Callable) -> Callable:
  """Mark ``callMeMaybe`` so the EZData hook ignores its name.

  The decorated function's body is discarded at class-creation
  time; ``EZMeta`` substitutes its own implementation. Use this
  decorator in an ``EZData`` class body when a type-checker needs
  to see a definition for one of the auto-generated dunders.
  """
  setattr(callMeMaybe, '__is_root__', True)
  return callMeMaybe
