on:
  workflow_dispatch:

jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Display OS
        run: lsb_release -a
      - name: Install custom software
        run: sudo apt-get update && sudo apt-get install -y tree
      - name: Show directory structure
        run: tree