name: Python Project from GitHub to PyPi

on:
  release:
    types: [ created ]

jobs:
  build-n-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - id: get-event-id
        uses: actions/event-id@v1
        with:
          event-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish distribution to PyPI
        env:
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ steps.get-event-id.outputs.event_id }}
        run: >-
          curl -X POST
          -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN"
          -F "content=@dist/*"
          https://upload.pypi.org/legacy/
