on:
  workflow_dispatch:

jobs:
  testJob:
    strategy:
      matrix:
        include:
          - python-version: '3.7'
            os: ubuntu-22.04
          - python-version: '3.8'
            os: ubuntu-latest
          - python-version: '3.9'
            os: ubuntu-latest
          - python-version: '3.10'
            os: ubuntu-latest
          - python-version: '3.11'
            os: ubuntu-latest
          - python-version: '3.12'
            os: ubuntu-latest
          - python-version: '3.13'
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
        continue-on-error: ${{ matrix.python-version == '3.13' }}

      - name: Inform if Python 3.13 is unavailable
        if: ${{ matrix.python-version == '3.13' && failure() }}
        run: |
          echo "Python 3.13 is not yet available in GitHub Actions."
          echo "Unit tests for versions 3.7 to 3.12 did pass successfully."
          echo "Publication will proceed."

      - name: Install Dependencies
        if: ${{ success() || matrix.python-version != '3.13' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Add project directory to PYTHONPATH
        if: ${{ success() || matrix.python-version != '3.13' }}
        run: echo "PYTHONPATH=${{ github.workspace }}/src" >> $GITHUB_ENV

      - name: Run Tests
        if: ${{ success() || matrix.python-version != '3.13' }}
        run: |
          python -m unittest discover -s tests

